/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 glasses.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/glasses.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Glasses.geometry}
        material={materials.oculos}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/glasses.glb");
